all: array printsum factorial

array: array.c
	gcc -g array.c -o array

printsum: printsum.c
	gcc -g printsum.c -o printsum

factorial: factorial.c
	gcc -g factorial.c -o factorial

clean:
	rm -f array
	rm -f printsum
	rm -f factorial
	rm -f core
