all: esempio esempio-corretto

esempio: esempio.c
	gcc -g esempio.c -o esempio

esempio-corretto: esempio-corretto.c
	gcc -g esempio-corretto.c -o esempio-corretto

clean:
	rm -f esempio
	rm -f esempio-corretto
	rm -f core
